use std::collections::HashSet;

// shamelessly generated by Copilot
pub fn primes_up_to(n: usize) -> Vec<usize> {
    if n < 2 {
        return Vec::new();
    }

    let mut sieve = vec![true; n + 1];
    sieve[0] = false;
    sieve[1] = false;

    let limit = (n as f64).sqrt() as usize;

    for i in 2..=limit {
        if sieve[i] {
            let mut j = i * i;
            while j <= n {
                sieve[j] = false;
                j += i;
            }
        }
    }

    sieve
        .iter()
        .enumerate()
        .filter_map(|(i, &is_prime)| is_prime.then_some(i))
        .collect()
}

pub fn big_little_omega(number: usize, mode: bool) -> usize {
    let primes = primes_up_to(number);
    let mut working_number = number;
    let mut factors: Vec<usize> = Vec::with_capacity(20);

    while working_number != 1 {
        for divisor in &primes {
            let division = working_number.div_euclid(*divisor);
            let remainder = working_number.rem_euclid(*divisor);
            if remainder == 0 {
                factors.push(*divisor);
                working_number = division;
                break;
            }
        }
    }
    if mode {
        factors.len()
    } else {
        factors.iter().collect::<HashSet<_>>().len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test1() {
        let result = big_little_omega(100061, false);
        assert_eq!(result, 3);
    }

    #[test]
    fn test2() {
        let result = big_little_omega(971088, false);
        assert_eq!(result, 3);
    }

    #[test]
    fn test3() {
        let result = big_little_omega(63640, true);
        assert_eq!(result, 6);
    }

    #[test]
    fn test4() {
        let result = big_little_omega(988841, true);
        assert_eq!(result, 2);
    }

    #[test]
    fn test5() {
        let result = big_little_omega(211529, false);
        assert_eq!(result, 2);
    }
}
